
### RGB LED
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led_o[*]}]
set_property SLEW SLOW [get_ports {rgb_led_o[*]}]
set_property DRIVE 4 [get_ports {rgb_led_o[*]}]

set_property PACKAGE_PIN R14 [get_ports {rgb_led_o[0]}]
set_property PACKAGE_PIN Y16 [get_ports {rgb_led_o[1]}]
set_property PACKAGE_PIN Y17 [get_ports {rgb_led_o[2]}]

### DIP Switch
set_property IOSTANDARD LVCMOS33 [get_ports {dip_sw_i[*]}]

set_property PACKAGE_PIN R19 [get_ports {dip_sw_i[0]}]
set_property PACKAGE_PIN T19 [get_ports {dip_sw_i[1]}]
set_property PACKAGE_PIN G14 [get_ports {dip_sw_i[2]}]
set_property PACKAGE_PIN J15 [get_ports {dip_sw_i[3]}]

### Beeper
create_bd_port -dir O beeper_o
set_property IOSTANDARD LVCMOS33 [get_ports {beeper_o}]
set_property SLEW SLOW [get_ports {beeper_o}]
set_property DRIVE 4 [get_ports {beeper_o}]
set_property PACKAGE_PIN P18 [get_ports {beeper_o}]

### Expansion connector on IO cape
set_property IOSTANDARD LVCMOS33 [get_ports {cape_p_io[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cape_n_io[*]}]
set_property SLEW FAST [get_ports {cape_p_io[*]}]
set_property SLEW FAST [get_ports {cape_n_io[*]}]
set_property DRIVE 8 [get_ports {cape_p_io[*]}]
set_property DRIVE 8 [get_ports {cape_n_io[*]}]

set_property PACKAGE_PIN B19 [get_ports {cape_p_io[0]}]
set_property PACKAGE_PIN A20 [get_ports {cape_n_io[0]}]
set_property PACKAGE_PIN E17 [get_ports {cape_p_io[1]}]
set_property PACKAGE_PIN D18 [get_ports {cape_n_io[1]}]
set_property PACKAGE_PIN D19 [get_ports {cape_p_io[2]}]
set_property PACKAGE_PIN D20 [get_ports {cape_n_io[2]}]
set_property PACKAGE_PIN E18 [get_ports {cape_p_io[3]}]
set_property PACKAGE_PIN E19 [get_ports {cape_n_io[3]}]
set_property PACKAGE_PIN F16 [get_ports {cape_p_io[4]}]
set_property PACKAGE_PIN F17 [get_ports {cape_n_io[4]}]
set_property PACKAGE_PIN M19 [get_ports {cape_p_io[5]}]
set_property PACKAGE_PIN M20 [get_ports {cape_n_io[5]}]
set_property PACKAGE_PIN M17 [get_ports {cape_p_io[6]}]
set_property PACKAGE_PIN M18 [get_ports {cape_n_io[6]}]
set_property PACKAGE_PIN L19 [get_ports {cape_p_io[7]}]
set_property PACKAGE_PIN L20 [get_ports {cape_n_io[7]}]
set_property PACKAGE_PIN K19 [get_ports {cape_p_io[8]}]
set_property PACKAGE_PIN J19 [get_ports {cape_n_io[8]}]
set_property PACKAGE_PIN L16 [get_ports {cape_p_io[9]}]
set_property PACKAGE_PIN L17 [get_ports {cape_n_io[9]}]
set_property PACKAGE_PIN H16 [get_ports {cape_p_io[10]}]
set_property PACKAGE_PIN K18 [get_ports {cape_n_io[10]}]
set_property PACKAGE_PIN J18 [get_ports {cape_p_io[11]}]
set_property PACKAGE_PIN H18 [get_ports {cape_n_io[11]}]
set_property PACKAGE_PIN F19 [get_ports {cape_p_io[12]}]
set_property PACKAGE_PIN F20 [get_ports {cape_n_io[12]}]
set_property PACKAGE_PIN G17 [get_ports {cape_p_io[13]}]
set_property PACKAGE_PIN G18 [get_ports {cape_n_io[13]}]
set_property PACKAGE_PIN J20 [get_ports {cape_p_io[14]}]
set_property PACKAGE_PIN H20 [get_ports {cape_n_io[14]}]
set_property PACKAGE_PIN G19 [get_ports {cape_p_io[15]}]
set_property PACKAGE_PIN G20 [get_ports {cape_n_io[15]}]
set_property PACKAGE_PIN H15 [get_ports {cape_p_io[16]}]
set_property PACKAGE_PIN G15 [get_ports {cape_n_io[16]}]
set_property PACKAGE_PIN K14 [get_ports {cape_p_io[17]}]
set_property PACKAGE_PIN J14 [get_ports {cape_n_io[17]}]
